/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        github: {
          bg: '#0d1117',
          border: '#30363d',
          'border-hover': '#8b949e',
          text: '#c9d1d9',
          'text-secondary': '#8b949e',
          'text-link': '#58a6ff',
          'text-danger': '#f85149',
          'text-success': '#3fb950',
          'text-warning': '#d29922',
          header: '#161b22',
          'header-border': '#21262d',
          sidebar: '#0d1117',
          'sidebar-border': '#30363d',
          canvas: '#0d1117',
          'canvas-inset': '#010409',
          'canvas-subtle': '#161b22',
          accent: '#1f6feb',
          'accent-emphasis': '#1f6feb',
          'accent-muted': '#388bfd',
          'accent-subtle': '#388bfd',
          danger: '#da3633',
          'danger-hover': '#f85149',
          success: '#238636',
          'success-emphasis': '#2ea043',
          warning: '#d29922',
          'warning-emphasis': '#d29922',
          btn: '#21262d',
          'btn-hover': '#30363d',
          'btn-primary': '#238636',
          'btn-primary-hover': '#2ea043',
          'btn-danger': '#da3633',
          'btn-danger-hover': '#f85149',
          'input-bg': '#0d1117',
          'input-border': '#30363d',
          'input-focus': '#1f6feb',
          'input-disabled': '#161b22',
          'dropdown-bg': '#161b22',
          'dropdown-border': '#30363d',
          'dropdown-hover': '#1f6feb',
          'menu-bg': '#0d1117',
          'menu-border': '#30363d',
          'menu-item-hover': '#161b22',
          'menu-item-selected': '#1f6feb',
          'overlay-bg': 'rgba(1, 4, 9, 0.8)',
          'overlay-border': '#30363d',
          'tooltip-bg': '#6e768166',
          'tooltip-border': '#8b949e',
          'timeline-connector': '#30363d',
          'timeline-item': '#0d1117',
          'timeline-item-border': '#30363d',
          'timeline-item-hover': '#161b22',
          'timeline-item-selected': '#1f6feb',
          'timeline-item-text': '#c9d1d9',
          'timeline-item-text-secondary': '#8b949e',
          'timeline-item-text-link': '#58a6ff',
          'timeline-item-text-danger': '#f85149',
          'timeline-item-text-success': '#3fb950',
          'timeline-item-text-warning': '#d29922',
          'timeline-item-bg': '#0d1117',
          'timeline-item-bg-hover': '#161b22',
          'timeline-item-bg-selected': '#1f6feb',
          'timeline-item-border': '#30363d',
          'timeline-item-border-hover': '#8b949e',
          'timeline-item-border-selected': '#1f6feb',
          'timeline-item-icon': '#8b949e',
          'timeline-item-icon-hover': '#c9d1d9',
          'timeline-item-icon-selected': '#ffffff',
          'timeline-item-icon-bg': '#0d1117',
          'timeline-item-icon-bg-hover': '#161b22',
          'timeline-item-icon-bg-selected': '#1f6feb',
          'timeline-item-icon-border': '#30363d',
          'timeline-item-icon-border-hover': '#8b949e',
          'timeline-item-icon-border-selected': '#1f6feb',
          'timeline-item-icon-text': '#8b949e',
          'timeline-item-icon-text-hover': '#c9d1d9',
          'timeline-item-icon-text-selected': '#ffffff',
          'timeline-item-icon-text-link': '#58a6ff',
          'timeline-item-icon-text-danger': '#f85149',
          'timeline-item-icon-text-success': '#3fb950',
          'timeline-item-icon-text-warning': '#d29922',
          'timeline-item-icon-text-bg': '#0d1117',
          'timeline-item-icon-text-bg-hover': '#161b22',
          'timeline-item-icon-text-bg-selected': '#1f6feb',
          'timeline-item-icon-text-border': '#30363d',
          'timeline-item-icon-text-border-hover': '#8b949e',
          'timeline-item-icon-text-border-selected': '#1f6feb',
          'timeline-item-icon-text-icon': '#8b949e',
          'timeline-item-icon-text-icon-hover': '#c9d1d9',
          'timeline-item-icon-text-icon-selected': '#ffffff',
          'timeline-item-icon-text-icon-bg': '#0d1117',
          'timeline-item-icon-text-icon-bg-hover': '#161b22',
          'timeline-item-icon-text-icon-bg-selected': '#1f6feb',
          'timeline-item-icon-text-icon-border': '#30363d',
          'timeline-item-icon-text-icon-border-hover': '#8b949e',
          'timeline-item-icon-text-icon-border-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text': '#8b949e',
          'timeline-item-icon-text-icon-text-hover': '#c9d1d9',
          'timeline-item-icon-text-icon-text-selected': '#ffffff',
          'timeline-item-icon-text-icon-text-link': '#58a6ff',
          'timeline-item-icon-text-icon-text-danger': '#f85149',
          'timeline-item-icon-text-icon-text-success': '#3fb950',
          'timeline-item-icon-text-icon-text-warning': '#d29922',
          'timeline-item-icon-text-icon-text-bg': '#0d1117',
          'timeline-item-icon-text-icon-text-bg-hover': '#161b22',
          'timeline-item-icon-text-icon-text-bg-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text-border': '#30363d',
          'timeline-item-icon-text-icon-text-border-hover': '#8b949e',
          'timeline-item-icon-text-icon-text-border-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text-icon': '#8b949e',
          'timeline-item-icon-text-icon-text-icon-hover': '#c9d1d9',
          'timeline-item-icon-text-icon-text-icon-selected': '#ffffff',
          'timeline-item-icon-text-icon-text-icon-bg': '#0d1117',
          'timeline-item-icon-text-icon-text-icon-bg-hover': '#161b22',
          'timeline-item-icon-text-icon-text-icon-bg-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text-icon-border': '#30363d',
          'timeline-item-icon-text-icon-text-icon-border-hover': '#8b949e',
          'timeline-item-icon-text-icon-text-icon-border-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text-icon-text': '#8b949e',
          'timeline-item-icon-text-icon-text-icon-text-hover': '#c9d1d9',
          'timeline-item-icon-text-icon-text-icon-text-selected': '#ffffff',
          'timeline-item-icon-text-icon-text-icon-text-link': '#58a6ff',
          'timeline-item-icon-text-icon-text-icon-text-danger': '#f85149',
          'timeline-item-icon-text-icon-text-icon-text-success': '#3fb950',
          'timeline-item-icon-text-icon-text-icon-text-warning': '#d29922',
          'timeline-item-icon-text-icon-text-icon-text-bg': '#0d1117',
          'timeline-item-icon-text-icon-text-icon-text-bg-hover': '#161b22',
          'timeline-item-icon-text-icon-text-icon-text-bg-selected': '#1f6feb',
          'timeline-item-icon-text-icon-text-icon-text-border': '#30363d',
          'timeline-item-icon-text-icon-text-icon-text-border-hover': '#8b949e',
          'timeline-item-icon-text-icon-text-icon-text-border-selected': '#1f6feb'
        }
      },
      fontFamily: {
        sans: ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Helvetica', 'Arial', 'sans-serif', 'Apple Color Emoji', 'Segoe UI Emoji'],
        mono: ['SFMono-Regular', 'Consolas', 'Liberation Mono', 'Menlo', 'monospace']
      },
      fontSize: {
        'xs': ['12px', { lineHeight: '18px' }],
        'sm': ['14px', { lineHeight: '21px' }],
        'base': ['16px', { lineHeight: '24px' }],
        'lg': ['18px', { lineHeight: '27px' }],
        'xl': ['20px', { lineHeight: '30px' }],
        '2xl': ['24px', { lineHeight: '36px' }],
        '3xl': ['30px', { lineHeight: '45px' }],
        '4xl': ['36px', { lineHeight: '54px' }]
      },
      animation: {
        'fade-in': 'fadeIn 0.15s ease-in-out',
        'slide-up': 'slideUp 0.15s ease-out',
        'spin': 'spin 1s linear infinite'
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(4px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
      boxShadow: {
        'sm': '0 1px 0 rgba(1, 4, 9, 0.04)',
        'DEFAULT': '0 1px 0 rgba(1, 4, 9, 0.04), 0 1px 3px rgba(1, 4, 9, 0.1)',
        'md': '0 3px 6px rgba(1, 4, 9, 0.1)',
        'lg': '0 8px 24px rgba(1, 4, 9, 0.12)',
        'xl': '0 12px 48px rgba(1, 4, 9, 0.15)',
        '2xl': '0 24px 48px rgba(1, 4, 9, 0.15), 0 1px 0 rgba(1, 4, 9, 0.04)',
        'inner': 'inset 0 1px 0 rgba(255, 255, 255, 0.05)',
        'none': 'none'
      },
      borderRadius: {
        'none': '0',
        'sm': '3px',
        'DEFAULT': '6px',
        'md': '6px',
        'lg': '12px',
        'xl': '16px',
        '2xl': '24px',
        '3xl': '32px',
        'full': '9999px'
      }
    },
  },
  plugins: [],
}